plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kiraworld.sarahtravel'
    compileSdk 35

    defaultConfig {
        applicationId 'com.kiraworld.sarahtravel'
        minSdk 26
        targetSdk 35
        versionCode 14
        versionName '1.4-public-web-fallback'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
