package com.kiraworld.sarahtravel;
import android.app.Activity; import android.content.Intent; import android.graphics.Typeface; import android.net.Uri; import android.os.Bundle; import android.view.ViewGroup; import android.widget.Button; import android.widget.LinearLayout; import android.widget.ScrollView; import android.widget.TextView; import java.text.DateFormat; import java.util.Date; import java.util.List; import java.util.Map;
public final class DiscoveryActivity extends Activity {
    @Override protected void onCreate(Bundle s){super.onCreate(s);ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,28,28,28);scroll.addView(root);TextView h=new TextView(this);h.setText("Sarah discoveries");h.setTextSize(28);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(h);
        TextView note=new TextView(this);note.setText("These are possible matches from connected public research. Sarah shows the source and time; a result is not proof that tickets, hours, access, or availability are current until you verify the official page.");note.setPadding(0,12,0,18);root.addView(note);
        SarahDatabase db=new SarahDatabase(this);PersonProfileStore people=new PersonProfileStore(this);String name;try{Map<String,String> owner=db.getProfile();people.ensureOwner(owner);Map<String,String> p=people.getActiveProfile();name=p.getOrDefault("name",owner.getOrDefault("name","Traveler"));}finally{people.close();db.close();}
        ProactiveDiscoveryStore store=new ProactiveDiscoveryStore(this);List<Map<String,String>> rows;try{rows=store.list(name,50);}finally{store.close();}
        if(rows.isEmpty()){TextView e=new TextView(this);e.setText("No discoveries are saved yet. Sarah researches only when connected research, automatic destination research, memory permission, and an active destination or approved nearby area are available.");root.addView(e);} else for(Map<String,String> row:rows){TextView title=new TextView(this);title.setText(row.get("title"));title.setTextSize(19);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setPadding(0,18,0,4);root.addView(title);TextView body=new TextView(this);body.setText(row.get("summary")+"\n\nSource: "+row.get("source")+"\nResearched: "+DateFormat.getDateTimeInstance().format(new Date(Long.parseLong(row.get("source_time")))));root.addView(body);Button open=new Button(this);open.setText("Open source and verify");open.setAllCaps(false);String url=row.get("url");open.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(url)));}catch(Exception ignored){}});root.addView(open);}
        Button refresh=new Button(this);refresh.setText("Research now");refresh.setAllCaps(false);refresh.setOnClickListener(v->{ProactiveDiscoveryScheduler.runSoon(this);refresh.setText("Research queued — check again shortly");});root.addView(refresh);setContentView(scroll);}
}
