package com.kiraworld.sarahtravel;
import android.content.Context; import android.util.Base64; import org.json.JSONArray; import org.json.JSONObject; import java.io.File; import java.nio.file.Files; import java.util.List; import java.util.Map;
public final class SarahSyncExporter {
    private SarahSyncExporter(){}
    public static JSONObject export(Context c)throws Exception{SarahDatabase db=new SarahDatabase(c);JSONObject out=new JSONObject();try{Map<String,String> profile=db.getProfile();out.put("schema","sarah-sync-v1");out.put("device_id",TrustedDeviceStore.localDeviceId(c));out.put("created_at",System.currentTimeMillis());out.put("profile",new JSONObject(profile));out.put("messages",array(db.recentMessages(200)));out.put("memories",memories(db.listMemories(200)));out.put("trips",trips(db.listTrips(100)));out.put("wishes",wishes(db.listWishes(100)));out.put("photos",photos(db.listPhotos(25)));MindEventStore mind=new MindEventStore(c);try{out.put("mind_events",mind.exportEncrypted(500));}finally{mind.close();}ProactiveDiscoveryStore discoveries=new ProactiveDiscoveryStore(c);try{out.put("discoveries",array(discoveries.list(profile.getOrDefault("name","Traveler"),100)));}finally{discoveries.close();}return out;}finally{db.close();}}
    private static JSONArray array(List<Map<String,String>> rows){JSONArray a=new JSONArray();for(Map<String,String> r:rows)a.put(new JSONObject(r));return a;}
    private static JSONArray memories(List<Map<String,String>> rows){JSONArray a=new JSONArray();for(Map<String,String> r:rows){JSONObject o=new JSONObject(r);try{o.put("memory_id","android-memory-"+Math.abs((r.getOrDefault("category","")+"|"+r.getOrDefault("summary","")).hashCode()));}catch(Exception ignored){}a.put(o);}return a;}
    private static JSONArray trips(List<Map<String,String>> rows){JSONArray a=new JSONArray();for(Map<String,String> r:rows){JSONObject o=new JSONObject(r);try{o.put("trip_id","android-trip-"+Math.abs((r.getOrDefault("title","")+"|"+r.getOrDefault("destination","")).hashCode()));}catch(Exception ignored){}a.put(o);}return a;}
    private static JSONArray wishes(List<Map<String,String>> rows){JSONArray a=new JSONArray();for(Map<String,String> r:rows){JSONObject o=new JSONObject(r);try{o.put("wish_id","android-wish-"+Math.abs(r.getOrDefault("destination","").toLowerCase().hashCode()));}catch(Exception ignored){}a.put(o);}return a;}
    private static JSONArray photos(List<Map<String,String>> rows){JSONArray a=new JSONArray();long total=0;for(Map<String,String> r:rows){try{File f=new File(r.getOrDefault("local_path",""));if(!f.isFile()||f.length()>3000000||total+f.length()>12000000)continue;JSONObject o=new JSONObject(r);o.put("jpeg_base64",Base64.encodeToString(Files.readAllBytes(f.toPath()),Base64.NO_WRAP));a.put(o);total+=f.length();}catch(Exception ignored){}}return a;}
}
